name: polaroid_journal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.2.1
  flutter_quill: ^11.5.0
  whiteboard: ^1.0.0
  flutter_svg: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: KrabbyPatty
      fonts:
        - asset: assets/fonts/KrabbyPatty.ttf
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/AbrilFatface.ttf
    - family: Akira
      fonts:
        - asset: assets/fonts/AkiraExpanded.otf
    - family: AppleGaramond
      fonts:
        - asset: assets/fonts/AppleGaramond.ttf
    - family: Moonlight
      fonts:
        - asset: assets/fonts/Moonlight.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Sekuya
      fonts:
        - asset: assets/fonts/Sekuya.ttf
    - family: Ransom
      fonts:
        - asset: assets/fonts/RansomNote.ttf
  assets:
    - assets/icons/
    - assets/images/

